### 1. register
POST https://localhost:3000/auth/register
Content-Type: application/json

{
    "userName": "johndoe12",
    "password": "securePassword1231"
}

### 2. login
POST https://localhost:3000/auth/login
Content-Type: application/json

{
    "userName": "johndoe12",
    "password": "securePassword1231"
}

### 3. adding to vault
POST https://localhost:3000/api/Item
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6ImpvaG5kb2UxMiIsImlkIjoiNjlmZWRkNjhiMjEzZjZkNmIyYzJiZmMzIiwiaWF0IjoxNzc4MzI0Nzc0LCJleHAiOjE3NzgzMjU2NzR9.XUVpq0kiyTjv-0SJeKr78ryPeTGdsB7guMwIPWqT2mc
Content-Type: application/json

{
    "name": "facebook.com",
    "value": "password123"
}
### delate
DELETE https://localhost:3000/api/Item
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6ImpvaG5kb2UxMiIsImlkIjoiNjlmZWRkNjhiMjEzZjZkNmIyYzJiZmMzIiwiaWF0IjoxNzc4MzI0Nzc0LCJleHAiOjE3NzgzMjU2NzR9.XUVpq0kiyTjv-0SJeKr78ryPeTGdsB7guMwIPWqT2mc

###specific delate
PATCH https://localhost:3000/api/Item/69ff175c513fcbb027f73b4b
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6ImpvaG5kb2UxMiIsImlkIjoiNjlmZWRkNjhiMjEzZjZkNmIyYzJiZmMzIiwiaWF0IjoxNzc4MzI0Nzc0LCJleHAiOjE3NzgzMjU2NzR9.XUVpq0kiyTjv-0SJeKr78ryPeTGdsB7guMwIPWqT2mc
Content-Type: application/json

### Get all items from the vault
GET https://localhost:3000/api/item
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6ImpvaG5kb2UxMiIsImlkIjoiNjlmZWRkNjhiMjEzZjZkNmIyYzJiZmMzIiwiaWF0IjoxNzc4MzI0Nzc0LCJleHAiOjE3NzgzMjU2NzR9.XUVpq0kiyTjv-0SJeKr78ryPeTGdsB7guMwIPWqT2mc