### 1. register
POST https://localhost:3000/auth/register
Content-Type: application/json

{
    "userName": "johndoe12",
    "password": "securePassword1231"
}

### 2. login
POST https://localhost:3000/auth/login
Content-Type: application/json

{
    "userName": "johndoe12",
    "password": "securePassword1231"
}

### 3. adding to vault
PATCH https://localhost:3000/api/Item
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6ImpvaG5kb2UxMiIsImlkIjoiNjlmZWRkNjhiMjEzZjZkNmIyYzJiZmMzIiwiaWF0IjoxNzc4MzE0MjY3LCJleHAiOjE3NzgzMTUxNjd9.u6htb_wrg9AX-8rYJ2Cb_7EARbFNO8d0pPixPbVT5cI
Content-Type: application/json

{
    "name": "facebook.com",
    "value": "password123"
}
### delate
DELETE https://localhost:3000/api/Item
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6ImpvaG5kb2UxMiIsImlkIjoiNjlmZWRkNjhiMjEzZjZkNmIyYzJiZmMzIiwiaWF0IjoxNzc4MzEzMTIyLCJleHAiOjE3NzgzMTQwMjJ9.OXtKMIRfDibN8UaklaIidm1vAD_Kqm7HoDjfxy8HQsw

###specific delate
PATCH https://localhost:3000/api/Item/69feec6b3b706ec13982c802
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6ImpvaG5kb2UxMiIsImlkIjoiNjlmZWRkNjhiMjEzZjZkNmIyYzJiZmMzIiwiaWF0IjoxNzc4MzE0MjY3LCJleHAiOjE3NzgzMTUxNjd9.u6htb_wrg9AX-8rYJ2Cb_7EARbFNO8d0pPixPbVT5cI
Content-Type: application/json

### Get all items in the vault
GET https://localhost:3000/api/item
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6ImpvaG5kb2UxMiIsImlkIjoiNjlmZWRkNjhiMjEzZjZkNmIyYzJiZmMzIiwiaWF0IjoxNzc4MzE0MjY3LCJleHAiOjE3NzgzMTUxNjd9.u6htb_wrg9AX-8rYJ2Cb_7EARbFNO8d0pPixPbVT5cI